[project]
name = "gradio-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.47.2",
    "google-genai>=0.2.0",
    "pillow>=11.0.0",
    "python-dotenv>=1.0.1",
]
